### ISSUE TITLE
Sign message return incorrect result

### ISSUE THREAD

**Issue by emn178** [TrustWallet/TrustCoreAndroid#1]
Latest Android app can't sign correctly by `web3.eth.sign`. It can sign but return incorrect result if with or without prefix: 
`\x19Ethereum Signed Message:\n`. I can't get correct signer by ecrecover.  Previous version can work with prefix. 

I also try `web3.personal.sign` but still not work.

Is this right project to report Android issues?

**Comment by vikmeup** [comment]
This is a wrong repo. 

You should be able to call sign or personal sign, these are the two separate methods on TrustSDK

**Comment by vikmeup** [comment]
Here is the correct repo: https://github.com/TrustWallet/TrustSDK-Android
